### ISSUE TITLE
Askbot requirement is unsupported version '1.5.x' of Django

### ISSUE THREAD

**Issue by KurtPfeifle** [ASKBOT/askbot-devel#470] opened 2015-05-30 10:48 UTC
Django versions 1.5 and 1.6 are both no longer supported. Askbot requires 1.5.x.

Are the developers of Askbot considering to port it to a newer, supported version of Django?

**Comment by evgenyfadeev** [comment] 2015-05-30 17:20
Yes, just the constraints of available time and other work (supporting
Askbot sites and helping customers using Askbot) are limiting.

On Sat, May 30, 2015 at 7:48 AM, Kurt Pfeifle <notifications@github.com>
wrote:

> Django versions 1.5 and 1.6 are both no longer supported. Askbot requires
> 1.5.x.
>
> Are the developers of Askbot considering to port it to a newer, supported
> version of Django?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ASKBOT/askbot-devel/issues/470>.
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by evgenyfadeev** [comment] 2015-07-12 21:23
Duplicate of other ticket requesting upgrade of Django support.

**Closed by evgenyfadeev** 2015-07-12 21:23 UTC
Labels: feature

**Comment by KurtPfeifle** [comment] 2015-07-12 21:35
For future readers: the "other ticket" seems to be #485.
